---

- name: Configure the windows hosts
  hosts:
    - windoze
  roles:
     #- { role: 'nxlog',
     #pkg_state: 'present',
     #service_start_mode: 'manual',
     #service_state: 'stopped' }

     - { role: 'nsclient',
     pkg_state: 'absent',
     service_start_mode: 'auto',
     service_state: 'started' }
