---

- name: Configure the windows hosts
  hosts:
    - windoze
  roles:
     #- { role: 'nxlog',
     #pkg_state: 'absent',
     #service_start_mode: 'manual',
     #service_state: 'stopped' }
     - { role: 'host-facts' }

- name: Configure bentos
  hosts:
    - bentos
  roles:
    - { role: 'host-facts' }
