---
# tasks file for host-facts
- name: Print hostname
  debug:
    msg: '{{ansible_hostname}}'

- name: Print OS Family
  debug:
    msg: '{{ansible_os_family}}'

- name: Run netstat (windows)
  win_command: 'netstat -a -p tcp'
  register: netstat_output_win
  when: ansible_os_family == 'Windows'

- name: Run netstat (linux)
  command: 'netstat -a -A inet'
  register: netstat_output_linux
  when: ansible_os_family != 'Windows'

- name: Print netstat output (windows)
  debug:
    msg: '{{netstat_output_win.stdout_lines}}'
  when: ansible_os_family == 'Windows'

- name: Print netstat output (windows)
  debug:
    msg: '{{netstat_output_linux.stdout_lines}}'
  when: ansible_os_family != 'Windows'
