---
# tasks file for nxlog, copies nxlog binary to host and
# performs win_msi install of it.
- name: Create C:\temp folder on host
  win_file:
    path: 'C:\\temp'
    state: directory

- name: Copy nxlog msi to host
  win_copy:
    src: 'files/{{msi_name}}'
    dest: 'C:\\temp\\{{msi_name}}'
  when: pkg_state == 'present'

# No 'when' statement on this as calling it with state: absent removes the
# windows services for us.
- name: Install nxlog msi file
  win_msi:
    path: 'C:\\temp\\{{msi_name}}'
    state: '{{pkg_state}}'
    creates: 'C:\\Program Files (x86)\\nxlog\\README.txt'

- name: Ensure windows service is in correct state.
  win_service:
    name: 'nxlog'
    start_mode: '{{service_start_mode}}'
    state: '{{service_state}}'
  when: pkg_state == 'present'

- name: Remove install directory if pkg_state == 'absent'
  win_file:
    path: 'C:\\Program Files (x86)\\nxlog'
    state: '{{pkg_state}}'
